service: weird-api

provider:
  name: aws
  runtime: nodejs8.10

functions:
  app:
    handler: index.handler
    events:
      - http: get /
      - http: get /cow
      - http: get /superheroes
      - http: get /superheroes/random
      - http: get /supervillians
      - http: get /supervillians/random
      - http: get /superb-like-words
